## ===== parameters 
#if $min_args > 0
    #set $length = len($arguments)
    #set $index = 0
    #for $arg in $arguments
        #if $arg.is_object and $generator.type_is_class($arg)
$generator.script_type_class_name($arg).replace("::",".") $argumtntTips[$index]#slurp
        #else
$generator.csharp_typename_from_native($arg) $argumtntTips[$index]#slurp
        #end if
        #if $index < $length - 1 
,#slurp
        #end if
        #set $index = $index + 1
    #end for
#end if
